// Add new people here. Clues go from hardest to easiest; every person needs the same number of clues (5).
// `aliases` are extra accepted answers (surnames, nicknames). Matching ignores case, accents and punctuation.
const P = (name, aliases, clues) => ({ id: name.toLowerCase().replace(/[^a-z0-9]+/g, '_'), name, aliases, clues });
const PEOPLE = [
  P('Albert Einstein', ['Einstein'], ['Born in Ulm, Germany, in 1879.', 'Won the Nobel Prize in Physics in 1921.', 'Published the theory of special relativity in 1905.', 'Gave the world the equation E = mc².', 'Physicist with famously wild white hair.']),
  P('Leonardo da Vinci', ['Leonardo', 'da Vinci'], ['Born in 1452 near a town in Tuscany, Italy.', 'Filled notebooks with designs for flying machines.', 'Painted The Last Supper.', 'Painted a portrait of Lisa Gherardini.', 'Painted the Mona Lisa.']),
  P('Marie Curie', ['Curie'], ['Born in Warsaw in 1867.', 'Coined the term "radioactivity".', 'Discovered the elements polonium and radium.', 'First person to win Nobel Prizes in two different sciences.', 'Pioneering scientist who worked with her husband Pierre.']),
  P('William Shakespeare', ['Shakespeare'], ['Born in Stratford-upon-Avon in 1564.', 'Married a woman named Anne Hathaway.', 'Was a shareholder in the Globe Theatre.', 'Wrote Hamlet and Macbeth.', 'The most famous playwright in the English language.']),
  P('Cleopatra', ['Cleopatra VII'], ['Died in 30 BC.', 'Last active ruler of Ptolemaic Egypt.', 'Allied with Julius Caesar.', 'Later partnered with the Roman general Mark Antony.', 'Famous queen of ancient Egypt.']),
  P('Nelson Mandela', ['Mandela'], ['Born in 1918 in the Eastern Cape.', 'Spent 27 years in prison.', 'Shared the 1993 Nobel Peace Prize with F. W. de Klerk.', 'Became president in 1994.', 'Anti-apartheid icon and first democratically elected president of South Africa.']),
  P('Muhammad Ali', ['Ali', 'Cassius Clay'], ['Born Cassius Clay in Louisville, Kentucky.', 'Won Olympic gold in 1960.', 'Fought the "Rumble in the Jungle" in 1974.', 'Said he would "float like a butterfly, sting like a bee".', 'Heavyweight boxing legend who called himself "The Greatest".']),
  P('Michael Jordan', ['Jordan'], ['Born in Brooklyn, New York, in 1963.', 'Played college basketball at North Carolina.', 'Briefly played minor league baseball.', 'Won six NBA titles with the Chicago Bulls.', 'Basketball legend famous for the number 23.']),
  P('Lionel Messi', ['Messi'], ['Born in Rosario, Argentina, in 1987.', 'Moved to Spain as a child to receive growth hormone treatment.', 'Holds the record for most Ballon d\'Or awards.', 'Captained Argentina to the 2022 World Cup title.', 'Argentine footballer who spent most of his career at Barcelona.']),
  P('Cristiano Ronaldo', ['Ronaldo', 'CR7'], ['Born in Funchal on the island of Madeira.', 'Played for Sporting, Manchester United, Real Madrid and Juventus.', 'Won the European Championship with Portugal in 2016.', 'Known by the nickname CR7.', 'Portuguese forward and one of football\'s all-time top scorers.']),
  P('Steve Jobs', ['Jobs'], ['Adopted as a baby and raised in California.', 'Was pushed out of his own company in 1985.', 'Bought the company that became Pixar.', 'Introduced the iPhone in 2007.', 'Co-founder of Apple.']),
  P('Bill Gates', ['Gates'], ['Born in Seattle in 1955.', 'Dropped out of Harvard.', 'Wrote early BASIC software for the Altair computer.', 'Founded a major charitable foundation focused on global health.', 'Co-founder of Microsoft.']),
  P('Taylor Swift', ['Swift'], ['Born in West Reading, Pennsylvania, in 1989.', 'Re-recorded her early albums to regain control of her masters.', 'Released albums titled 1989 and Folklore.', 'Her Eras Tour became one of the biggest tours ever.', 'Pop superstar whose fans are called Swifties.']),
  P('Barack Obama', ['Obama'], ['Born in Honolulu, Hawaii, in 1961.', 'Worked as a community organizer in Chicago.', 'Won the Nobel Peace Prize in 2009.', 'Served as the 44th President of the United States.', 'First Black president of the United States.']),
  P('Queen Elizabeth II', ['Elizabeth II', 'Queen Elizabeth', 'Elizabeth'], ['Born in London in 1926.', 'Trained as a truck mechanic during World War II.', 'Became queen in 1952 while abroad in Kenya.', 'Reigned for 70 years.', 'Longest-reigning British monarch.']),
  P('Mahatma Gandhi', ['Gandhi', 'Mohandas Gandhi'], ['Trained as a lawyer in London.', 'Spent about two decades in South Africa.', 'Led the Salt March in 1930.', 'Led India\'s non-violent independence movement.', 'Known as "Mahatma", meaning "great soul".']),
  P('Pelé', ['Pele', 'Edson Arantes do Nascimento'], ['Born Edson Arantes do Nascimento.', 'Won his first World Cup at age 17.', 'Spent most of his club career at Santos.', 'Won three World Cups with Brazil.', 'Brazilian football legend known by a one-word nickname.']),
  P('Serena Williams', ['Serena'], ['Born in Saginaw, Michigan, in 1981.', 'Won her first Grand Slam singles title at the 1999 US Open.', 'Her sister Venus is also a champion.', 'Won 23 Grand Slam singles titles.', 'American tennis legend.']),
  P('Neil Armstrong', ['Armstrong'], ['Born in Ohio in 1930.', 'Flew as a Navy pilot in the Korean War.', 'Commanded the Apollo 11 mission.', 'Spoke of "one small step for man".', 'First person to walk on the Moon.']),
  P('Frida Kahlo', ['Kahlo'], ['Born in Coyoacán, Mexico City, in 1907.', 'Survived a serious bus accident as a teenager.', 'Married the muralist Diego Rivera.', 'Famous for her many self-portraits.', 'Iconic Mexican painter.']),
  P('Wolfgang Amadeus Mozart', ['Mozart'], ['Born in Salzburg in 1756.', 'Began composing at age five.', 'Wrote The Marriage of Figaro and The Magic Flute.', 'Died at only 35.', 'Child prodigy composer of the Classical era.']),
  P('Bruce Lee', ['Lee'], ['Born in San Francisco in 1940.', 'Grew up in Hong Kong.', 'Founded the martial art Jeet Kune Do.', 'Starred in Enter the Dragon.', 'Martial arts film legend.']),
];
module.exports = { PEOPLE };
